import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Home Page</title>
      </head>
      <body>
        <header>
          <h1 className="text-center">Header</h1>
        </header>
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
          {children}
        </main>
        <footer>
          <h1 className="text-center">Footer</h1>
        </footer>
      </body>
    </html>
  );
}
